version: '3.7'

services:
  backend:
    image: backend
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8010:8010
  frontend:
    image: frontend
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8020:80
    depends_on:
      - backend
